---
name: Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  lza-module-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@7a4417e281f2b6fc8a8271b634bebeb11a7065e0 # main
    name: Landing Zone Module Validation
    with:
      working-directory: "modules/lza"

  cost-module-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@7a4417e281f2b6fc8a8271b634bebeb11a7065e0 # main
    name: Cost Analysis Module Validation
    with:
      working-directory: "modules/costanalysis"
