name: Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - vnext

jobs:
  root-module-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@main
    name: Root Module Validation

  lza-module-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@main
    name: Root Module Validation
    with:
      working-directory: "modules/lza"
