name: Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - vnext

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  lza-module-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@main
    name: Landing Zone Module Validation
    with:
      working-directory: "modules/lza"

  cost-module-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@main
    name: Cost Analysis Module Validation
    with:
      working-directory: "modules/costanalysis"
