---
name: Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  lza-module-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@f2a5b0a646a988f5a0e80df7447aede6c07bbb44 # main
    name: Landing Zone Module Validation
    with:
      working-directory: "modules/lza"

  cost-module-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@f2a5b0a646a988f5a0e80df7447aede6c07bbb44 # main
    name: Cost Analysis Module Validation
    with:
      working-directory: "modules/costanalysis"
